# Generated by Django 2.0.5 on 2018-05-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_saleorder_saleorderline'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='total_sale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='saleorderline',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
